import type { Metadata } from "next";
import { LegalPage, Section } from "@/app/legal-ui";

export const metadata: Metadata = {
  title: "Privacy Policy · Nspiire",
  description: "What Nspiire collects, why, and how to remove it.",
};

/**
 * Written to match what the code actually does. If the data handling changes,
 * this page has to change with it — TikTok's app review checks that a privacy
 * policy describes real behaviour, and a policy that drifts from the product
 * is worse than none.
 *
 * Sources of truth for the claims below:
 *   src/lib/tiktok/client.ts   which fields are requested
 *   src/lib/tiktok/sync.ts     what is stored and when
 *   src/lib/creators/metrics.ts what is derived
 */
export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="31 August 2026">
      <Section heading="Who we are">
        <p>
          Nspiire is operated by VerMar Design LLC (&ldquo;we&rdquo;). We can be
          reached at wes@vermardesign.com.
        </p>
      </Section>

      <Section heading="What we collect">
        <p>
          <strong className="font-medium">Account details you give us.</strong> Your
          name, email address, niche, rate card, negotiating guardrails, and any
          notes you enter about your voice or preferences.
        </p>
        <p>
          <strong className="font-medium">TikTok data, only if you connect your
          account.</strong> When you authorise Nspiire through TikTok Login, we read,
          from your own account only:
        </p>
        <ul className="ml-5 list-disc space-y-1">
          <li>your profile — account identifier, display name, avatar, bio, verified status</li>
          <li>your account statistics — follower count, following count, total likes, video count</li>
          <li>
            statistics for your recent posts — view, like, comment and share counts.
            We read these counts only; we do not download or store your videos.
          </li>
        </ul>
        <p>
          We read no data about any other TikTok user. Nspiire cannot post,
          comment, message, or take any other action on your account — the access
          we request is read-only.
        </p>
      </Section>

      <Section heading="Why we collect it">
        <p>
          Your follower count and post statistics are used to compute your average
          views and engagement rate. Those figures do two things: they let us
          suggest brands whose usual creator partnerships match your size and
          niche, and they inform the sponsorship rate we recommend when you price
          a deal. Without them the product cannot do either, and we would be
          guessing at numbers that determine what you get paid.
        </p>
      </Section>

      <Section heading="What we do not do">
        <p>
          We do not sell your data. We do not share it with advertisers or data
          brokers. We do not use it to train machine-learning models. Your metrics
          are not shown to other creators.
        </p>
        <p>
          Brand suggestions are generated by an AI model (Anthropic&rsquo;s Claude).
          It receives your niche, your audience size and engagement figures, and
          your guardrails. It does not receive your email address, your contacts,
          or your deal history.
        </p>
      </Section>

      <Section heading="Where it is stored">
        <p>
          Data is stored in a Postgres database hosted in the United States, and
          the application is hosted on Vercel. Access tokens issued by TikTok are
          stored so we can refresh your metrics; they are used for nothing else.
        </p>
      </Section>

      <Section heading="Removing your data">
        <p>
          You can disconnect TikTok at any time, from your creator page in Nspiire
          or from TikTok&rsquo;s own third-party app settings. Disconnecting stops
          any further syncing immediately.
        </p>
        <p>
          To have your stored data deleted, email wes@vermardesign.com. We will delete
          your creator record, your synced metrics, and any TikTok tokens we hold
          within 30 days, and confirm when it is done.
        </p>
      </Section>

      <Section heading="Changes">
        <p>
          If we change what we collect or what we do with it, we will update this
          page and change the date at the top.
        </p>
      </Section>
    </LegalPage>
  );
}
